"""initial schema

Revision ID: 9c071761d394
Revises: 
Create Date: 2026-08-19 01:09:35.965454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c071761d394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chcs_name'), 'chcs', ['name'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_name'), 'farmers', ['name'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=80), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_farmer_id'), 'fields', ['farmer_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chc_id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('operating_radius', sa.Float(), nullable=False),
    sa.Column('maintenance_status', sa.String(length=30), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=False),
    sa.Column('current_longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chc_id'], ['chcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_chc_id'), 'machines', ['chc_id'], unique=False)
    op.create_index(op.f('ix_machines_machine_type'), 'machines', ['machine_type'], unique=False)
    op.create_table('demand_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=80), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_requests_farmer_id'), 'demand_requests', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_demand_requests_field_id'), 'demand_requests', ['field_id'], unique=False)
    op.create_index(op.f('ix_demand_requests_requested_date'), 'demand_requests', ['requested_date'], unique=False)
    op.create_index(op.f('ix_demand_requests_status'), 'demand_requests', ['status'], unique=False)
    op.create_table('machine_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_availability_date'), 'machine_availability', ['date'], unique=False)
    op.create_index(op.f('ix_machine_availability_machine_id'), 'machine_availability', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_availability_status'), 'machine_availability', ['status'], unique=False)
    op.create_table('relocation_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('from_chc_id', sa.Integer(), nullable=False),
    sa.Column('to_cluster', sa.String(length=80), nullable=False),
    sa.Column('machine_type', sa.String(length=80), nullable=False),
    sa.Column('net_benefit', sa.Float(), nullable=False),
    sa.Column('relocation_cost', sa.Float(), nullable=False),
    sa.Column('expected_revenue', sa.Float(), nullable=False),
    sa.Column('expected_farmers_served', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('benefit_breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_chc_id'], ['chcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relocation_recommendations_from_chc_id'), 'relocation_recommendations', ['from_chc_id'], unique=False)
    op.create_index(op.f('ix_relocation_recommendations_machine_id'), 'relocation_recommendations', ['machine_id'], unique=False)
    op.create_index(op.f('ix_relocation_recommendations_status'), 'relocation_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_relocation_recommendations_to_cluster'), 'relocation_recommendations', ['to_cluster'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('depot_latitude', sa.Float(), nullable=False),
    sa.Column('depot_longitude', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_travel_time_min', sa.Integer(), nullable=False),
    sa.Column('total_route_duration_min', sa.Integer(), nullable=False),
    sa.Column('returned_to_depot', sa.Boolean(), nullable=False),
    sa.Column('dropped_stop_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_machine_id'), 'routes', ['machine_id'], unique=False)
    op.create_index(op.f('ix_routes_status'), 'routes', ['status'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('is_depot', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('arrival_min', sa.Integer(), nullable=False),
    sa.Column('service_start_min', sa.Integer(), nullable=False),
    sa.Column('service_end_min', sa.Integer(), nullable=False),
    sa.Column('service_duration_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_machine_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_relocation_recommendations_to_cluster'), table_name='relocation_recommendations')
    op.drop_index(op.f('ix_relocation_recommendations_status'), table_name='relocation_recommendations')
    op.drop_index(op.f('ix_relocation_recommendations_machine_id'), table_name='relocation_recommendations')
    op.drop_index(op.f('ix_relocation_recommendations_from_chc_id'), table_name='relocation_recommendations')
    op.drop_table('relocation_recommendations')
    op.drop_index(op.f('ix_machine_availability_status'), table_name='machine_availability')
    op.drop_index(op.f('ix_machine_availability_machine_id'), table_name='machine_availability')
    op.drop_index(op.f('ix_machine_availability_date'), table_name='machine_availability')
    op.drop_table('machine_availability')
    op.drop_index(op.f('ix_demand_requests_status'), table_name='demand_requests')
    op.drop_index(op.f('ix_demand_requests_requested_date'), table_name='demand_requests')
    op.drop_index(op.f('ix_demand_requests_field_id'), table_name='demand_requests')
    op.drop_index(op.f('ix_demand_requests_farmer_id'), table_name='demand_requests')
    op.drop_table('demand_requests')
    op.drop_index(op.f('ix_machines_machine_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_chc_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_fields_farmer_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_farmers_name'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_chcs_name'), table_name='chcs')
    op.drop_table('chcs')
    # ### end Alembic commands ###
