"""add bookings table

Revision ID: e9e811b0afcb
Revises: ab0103d47017
Create Date: 2026-08-19 17:20:31.228560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e811b0afcb'
down_revision: Union[str, Sequence[str], None] = 'ab0103d47017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_request_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demand_request_id'], ['demand_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_demand_request_id'), 'bookings', ['demand_request_id'], unique=True)
    op.create_index(op.f('ix_bookings_machine_id'), 'bookings', ['machine_id'], unique=False)
    op.create_index(op.f('ix_bookings_route_id'), 'bookings', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_route_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_machine_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_demand_request_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
